### PR TITLE
fix(heater-shaker): set thermal offset constants if not set

### LINKED ISSUE #358: fix(heater-shaker): set thermal offset constants if not set

### PR DESCRIPTION
**Pull request by pmoegenburg**
Closes #358

### CODE REVIEW

**Comment by pmoegenburg** [comment]
Updating tests

File: stm32-modules/include/heater-shaker/heater-shaker/flash.hpp [hunk 1]
```diff
@@ -99,6 +105,8 @@ class Flash {
   private:
     /** Default value for all constants.*/
     static constexpr double OFFSET_DEFAULT_CONST = 0.0F;
```
Comment (fsinapi) [inline stm32-modules/include/heater-shaker/heater-shaker/flash.hpp]: Could probably get rid of this constant now, a little misleading since this _isn't_ the default anymore

File: stm32-modules/include/heater-shaker/heater-shaker/flash.hpp [hunk 2]
```diff
@@ -60,6 +60,12 @@ class Flash {
             static_cast<uint64_t>(FLASHFlag::WRITTEN_NO_CHECKSUM)) {
             ret.b = receive.b;
             ret.c = receive.c;
+        } else {
+            OffsetConstants constants = {.b = OFFSET_B_DEFAULT_CONST, .c = OFFSET_C_DEFAULT_CONST, .flag = static_cast<uint64_t>(flash::Flash::FLASHFlag::WRITTEN_NO_CHECKSUM)};
+            if (set_offset_constants(constants, policy)) {
+                ret.b = OFFSET_B_DEFAULT_CONST;
```
Comment (fsinapi) [inline stm32-modules/include/heater-shaker/heater-shaker/flash.hpp]: If the constants can't get overwritten, I would think that you'd still want to return the defaults.

**Review by fsinapi — COMMENTED** [review]
Nice, just a couple of _very_ minor things. I'll give it another pass when tests are up.

File: stm32-modules/include/heater-shaker/heater-shaker/flash.hpp (hunk 1 above)
Comment (pmoegenburg) [reply stm32-modules/include/heater-shaker/heater-shaker/flash.hpp:109]: updated

**Review by sfoster1 — APPROVED** [review]
Looks good to me!

**Review by fsinapi — APPROVED** [review]
Looks good to me!
